"""empty message

Revision ID: 15ca03fca9be
Revises: 7d6f89bc1cbb
Create Date: 2024-04-24 12:30:15.438395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15ca03fca9be'
down_revision = '7d6f89bc1cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=250), nullable=False))
        batch_op.drop_column('subscripcion_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscripcion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
