"""empty message

Revision ID: 9b364f5d7e9f
Revises: c45122b4d600
Create Date: 2024-04-19 10:06:58.858102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b364f5d7e9f'
down_revision = 'c45122b4d600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('age',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    op.drop_table('favorite_characters')
    # ### end Alembic commands ###
